### ISSUE TITLE
No Module Named Termcolor

### ISSUE THREAD

**Issue by manves** [BusesCanFly/PRETty#1]
┌──(root💀DESKTOP-A0L2F3U)-[~/PRET/PRETty]
└─# ./PRETty.py                             
Traceback (most recent call last):
  File "./PRETty.py", line 6, in <module>
    from termcolor import colored, cprint
ImportError: No module named termcolor

**Comment by TuVeKoi** [comment]
> ┌──(root💀DESKTOP-A0L2F3U)-[~/PRET/PRETty] └─# ./PRETty.py Traceback (most recent call last): File "./PRETty.py", line 6, in from termcolor import colored, cprint ImportError: No module named termcolor

1: you have to install pip2

2: pip2 install termcolor

3: python2 PRETty.py
DONE
